#import "../../appx/theme.typ": tufte, meta, note

#show: tufte

#meta(
  subtitle: [Product of exponentials and robot description],
  source: [Modern Robotics],
  revised: [2026-07-13],
  tags: ("robotics", "modern-robotics", "modo"),
)

#let argmin = math.op("arg min", limits: true)
#let exp = math.op("exp")
#let log = math.op("log")
#let sin = math.op("sin")
#let cos = math.op("cos")
#let tan = math.op("tan")
#let atan2 = math.op("atan2")
#let rank = math.op("rank")
#let det = math.op("det")
#let tr = math.op("tr")
#let Ad = math.op("Ad")
#let ad = math.op("ad")
#let J = math.op("J")
#let diag = math.op("diag")
#let null = math.op("null")
#let span = math.op("span")
#let sign = math.op("sign")
#let sat = math.op("sat")
#let dot = math.op("dot")
#let ddot = math.op("ddot")

= Chapter 4: Forward Kinematics

Forward kinematics maps joint coordinates to the configuration of a chosen
end-effector frame.  The product-of-exponentials (POE) model separates the
description of the mechanism at its home position from the motion generated by
each joint.  This makes the formula compact, frame-aware, and suitable for both
analysis and implementation.

== Problem and Representation

For an $n$-joint open chain, forward kinematics is the map

$ theta = (theta_1, dots, theta_n) arrow.r T(theta) in "SE"(3). $

The task space depends on what is relevant: position only, planar pose, or the
full spatial pose.  A spatial rigid-body configuration is represented by

$ T = mat(R, p; 0, 1), quad R in "SO"(3), quad p in RR^3. $

For a planar 3R arm with link lengths $L_i$, direct geometry gives

$ x &= L_1 cos theta_1 + L_2 cos(theta_1+theta_2)
     + L_3 cos(theta_1+theta_2+theta_3), \
  y &= L_1 sin theta_1 + L_2 sin(theta_1+theta_2)
     + L_3 sin(theta_1+theta_2+theta_3), \
  phi &= theta_1+theta_2+theta_3. $

Multiplying link-to-link transforms also works, but introduces a frame on every
link.  POE needs only one fixed frame, one end-effector frame, the home pose,
and one screw axis per joint.

== Screw Axes

A normalized screw axis combines angular and linear velocity:

$ cal(S) = mat(omega; v) in RR^6, quad norm(omega) = 1 $

for a revolute or helical joint.  Its matrix representation is

$ [cal(S)] = mat([omega], v; 0, 0) in frak(s e)(3). $

The joint geometry determines $(omega,v)$:

- *Revolute:* for a unit axis $omega$ through any point $q$,
  $v=-omega times q$.
- *Prismatic:* for unit translation direction $v$, $omega=0$.
- *Helical:* with pitch $h$, $v=-omega times q+h omega$; one radian of
  rotation advances the joint by $h$.

The choice of $q$ along the revolute axis is immaterial.  If
$q' = q + lambda omega$, then $-omega times q'=-omega times q$.

#note[The six entries of a screw axis are not a point and an angle.  They are
the instantaneous angular and linear velocity of a frame when the joint rate
is one.]

== Exponential Coordinates

The exponential $e^([cal(S)] theta)$ integrates a constant screw motion.  For a
revolute or helical joint,

$ e^([cal(S)] theta)
  = mat(e^([omega] theta),
      (I theta + (1-cos theta)[omega]
      + (theta-sin theta)[omega]^2)v;
      0, 1). $

For a prismatic joint,

$ e^([cal(S)] theta) = mat(I, v theta; 0, 1). $

For unit $omega$, the skew matrix satisfies
$[omega]^3=-[omega]$ and $[omega]^4=-[omega]^2$.  Splitting the matrix
exponential series into odd and even powers gives

$ e^([omega]theta)
  &=I+[omega](theta-theta^3/3!+theta^5/5!-dots) \
  &quad +[omega]^2(theta^2/2!-theta^4/4!+dots) \
  &=I+sin theta[omega]+(1-cos theta)[omega]^2. $

For the homogeneous exponential, the rotational block is
$R(theta)=e^([omega]theta)$ and its translation obeys
$dot(p)(theta)=R(theta)v$, $p(0)=0$.  Therefore

$ p(theta)=integral_0^theta e^([omega]sigma)v d sigma. $

Integrating the Rodrigues coefficients yields

$ p(theta)=(I theta+(1-cos theta)[omega]
  +(theta-sin theta)[omega]^2)v, $

which derives the twist exponential above.  When $omega=0$, the integral
reduces to $p(theta)=v theta$.

Here $theta$ is an angle for a revolute joint and a distance for a prismatic
joint.  The order of exponentials matters because rigid transformations do not
commute.  Left multiplication expresses a motion in the fixed frame; right
multiplication expresses it in the moving body frame.

== Space POE Formula

Set all joint variables to zero and record the home configuration
$M=T(0)$.  Express every joint screw axis in the fixed space frame at this same
home configuration.  Then

$ T(theta) = e^([cal(S)_1] theta_1)
  e^([cal(S)_2] theta_2) dots
  e^([cal(S)_n] theta_n) M. $

The exponentials appear in joint order from base to end effector.  Although
$cal(S)_i$ is recorded at home, the preceding exponentials automatically move
its physical axis to the current configuration.

This follows from conjugation.  If $T$ carries a screw coordinate frame to the
space frame, then

$ T e^([cal(S)]theta)T^(-1)
  =e^(T[cal(S)]T^(-1)theta)
  =e^([Ad_T cal(S)]theta). $

After joints $1,dots,i-1$ move, the current space screw of joint $i$ is

$ cal(S)_i(theta)=Ad_(e^([cal(S)_1]theta_1)dots
  e^([cal(S)_(i-1)]theta_(i-1)))cal(S)_i. $

Applying each joint motion to the chain already moved by its predecessors gives
the ordered product inductively.

== Body POE Formula

Alternatively, express every screw axis in the end-effector frame at home:

$ T(theta) = M e^([cal(B)_1] theta_1)
  e^([cal(B)_2] theta_2) dots
  e^([cal(B)_n] theta_n). $

The ordering of the joint variables is unchanged; only the side on which the
motion product acts is different.  Space and body descriptions are equivalent:

$ cal(S)_i = Ad_M cal(B)_i,
  quad cal(B)_i = Ad_(M^(-1)) cal(S)_i. $

To derive the body form, use the conjugation identity

$ e^([cal(S)_i]theta_i)M
  =M(M^(-1)e^([cal(S)_i]theta_i)M)
  =M e^([Ad_(M^(-1))cal(S)_i]theta_i). $

Repeatedly moving $M$ left through the space exponentials produces the body
POE and proves $cal(B)_i=Ad_(M^(-1))cal(S)_i$.

For a body-frame construction, it is often easiest to imagine locking every
joint except joint $i$, moving $theta_i$ positively, and observing the
instantaneous screw of the end-effector frame expressed in ${b}$.

== Adjoint

For $T = mat(R, p; 0, 1)$:

$ Ad_T = mat(R, 0; [p]R, R) $

It transforms twists:

$ cal(V)_s = Ad_T cal(V)_b $

and satisfies the composition rule

$ Ad_(T_1 T_2) = Ad_(T_1) Ad_(T_2),
  quad Ad_(T^(-1)) = (Ad_T)^(-1). $

The block form can be derived rather than memorized.  For
$T=mat(R,p;0,1)$ and $[cal(V)]=mat([omega],v;0,0)$,

$ T[cal(V)]T^(-1)
  =mat(R[omega]R^T,-R[omega]R^T p+R v;0,0). $

Since $R[omega]R^T=[R omega]$ and
$-[R omega]p=[p]R omega$, its vector coordinates are

$ mat(R omega;[p]R omega+R v)
  =mat(R,0;[p]R,R)mat(omega;v)=Ad_T cal(V). $

Thus the adjoint changes coordinates without changing the physical twist.

== Takeaway

Forward kinematics is completely specified by a home configuration and an
ordered list of joint screws.  The space and body POE formulas describe the same
motion in different coordinates, with the adjoint providing the conversion.
